name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true
  REGISTRY: ghcr.io

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published == 'true' }}

      # The published packages output from the changsets action is a stringified JSON array.
      # For example: '[{"name":"@labshare/auth","version":"6.6.0"},{"name":"@labshare/auth-ui","version":"3.3.1"}]'.
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure CI Github User
        run: |
          git config --global user.name 'LabShare'
          git config --global user.email 'LabShare@labshare.org'
          git remote set-url origin https://$GITHUB_ACTOR:$GH_TOKEN@github.com/ncats/auth-monorepo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: npm install
        with:
          npm-token: ${{secrets.NPM_INSTALL_TOKEN}}

      # Changesets action reuses the .npmrc if it already exists. In this case, we
      # need to change to an NPM token with write access.
      - run: rm ~/.npmrc
        shell: "bash"

      - name: create and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: npm ci:publish
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  